name: Manual UnicornSignUp test

on:
  workflow_dispatch:
    inputs:
      test_class:
        description: 'Test class to run'
        default: 'UnicornSignUp'
        required: true
        type: string
      browser:
        description: 'Browser to run tests on'
        default: 'chrome'
        required: true
        type: string
      emailAddress:
        description: 'Email address for login'
        default: 'test@example.com'
        required: true
        type: string

jobs:
  run-unicorn-signup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          
      - name: Install Chrome
        run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
          
      - name: Run specified test class
        run: mvn -B -Dtest="${{ github.event.inputs.test_class }}" -Dbrowser="${{ github.event.inputs.browser }}" -DemailAddress="${{ github.event.inputs.emailAddress }}" test

      - name: Upload Report Files
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: target/ExtentReport
          retention-days: 5
          
